### PR TITLE
add yarn prepare command for husky

### PR DESCRIPTION
**Pull request by acharb**
running `yarn prepare` will set up a dev's machine for the husky hooks

### CODE REVIEW

**Comment by acharb** [comment]
@CassioMG ok I figured it out. The husky hook needs to be added to each person's local machine, and is added when `husky install` is ran.

can you run `yarn prepare` when you get the chance, and add another test commit to check it's working?

**Comment by CassioMG** [comment]
> @CassioMG ok I figured it out. The husky hook needs to be added to each person's local machine, and is added when `husky install` is ran.
> 
> can you run `yarn prepare` when you get the chance, and add another test commit to check it's working?

@acharb ok looks like it worked now :)
I pushed a [completely messed up commit](https://github.com/stellar/typescript-wallet-sdk/pull/50/commits/b0cb4778a6b87983592a854a1fd998704d704dcd) and it only left 2 blank lines

**Comment by CassioMG** [comment]
@acharb just FYI, on Vibrant we use the below packages which help us keeping a very consistent codebase in regards to code formatting, typing, syntax and also detecting unused code (like unused imports which I see happens quite often in our typescript-wallet-sdk repo, also works for unused functions):
"@stellar/eslint-config": "^2.1.2", ===> we already use this on the TS repo
"@stellar/prettier-config": "^1.0.1", ===> we already use this on the TS repo
"@stellar/tsconfig": "^1.0.2", ===> we already use this on the TS repo
"prettier": "^2.6.0", ===> we already use this on the TS repo (but on version 2.0.5)
"@typescript-eslint/eslint-plugin": "^5.15.0",  ===> new to TS repo
"@typescript-eslint/parser": "^5.15.0", ===> new to TS repo
"@fnando/eslint-plugin-consistent-import": "*", ===> new to TS repo
"babel-eslint": "^10.0.3", ===> new to TS repo
"eslint-config-prettier": "^8.6.0", ===> new to TS repo
"eslint-plugin-prettier": "^4.0.0", ===> new to TS repo
"ts-prune": "^0.10.3", ===> new to TS repo

we also use some scripts in addition to those imports, so maybe some of them wouldn't work out of the box but thought about sharing it in case you'd like to take a look :)

**Comment by acharb** [comment]
awesome I'll look through these. I was hesitant to add linting at the start but there's a [ticket](https://stellarorg.atlassian.net/browse/WAL-1046?atlOrigin=eyJpIjoiZTBmMTVmNGRkZmU3NGUwODhhYWJlZmUwMGRlMTE1YzEiLCJwIjoiaiJ9) to add it now that it's public. I'll add this to the ticket thanks!

**Pull request merged**
