### PR TITLE
add sep10 sign challenge txn helper

### PR DESCRIPTION
**Pull request by acharb**
[ticket](https://stellarorg.atlassian.net/browse/WAL-1235?atlOrigin=eyJpIjoiMzNlYjg0NThkYTcyNDY2ZWIyNjEwNzBiMzgzZGQ4YWQiLCJwIjoiaiJ9)

validates
- sequence num is 0
- signed by anchor

then returns signed txn

### CODE REVIEW

**Review by piyalbasu — APPROVED** [review]

**Comment by Ifropc** [comment]
This is for server side, right? Can we move it to a different place so developer won't confuse it for client side signing?

**Comment by acharb** [comment]
> This is for server side, right? Can we move it to a different place so developer won't confuse it for client side signing?

I left it in the main walletSdk because it _can_ be used for either client or server side right?

**Comment by Ifropc** [comment]
I think it's technically only for server, because it's used to sign client domain challenge (which must only be on the server)

**Comment by acharb** [comment]
@Ifropc  gotchya, hows this then?
https://github.com/stellar/typescript-wallet-sdk/pull/95/commits/2b7cfbbf4d9205e56ca8d1494750880d10eec694

**Comment by acharb** [comment]
hmm we already have a `Utils` module at that level, having two Utils at same level might be a little repetitive?

Will merge this in though but open to changing the name

**Pull request merged**
